@startuml

component [PRO] <<Environment>> as pro

component [CDN] <<Stack>> as cdn
component [mails] <<Stack>> as mails
component [hosted_zones] <<Stack>> as dns

component [aws_acm_certificate] <<Module>> as cert
component [aws_s3_bucket] <<Module>> as s3
component [redirect] <<Module>> as redirect
component [SES 1] <<Module>> as ses1
component [SES 2] <<Module>> as ses2
component [Email Identity] <<Module>> as email
component [hosting_zone_1] <<Module>> as zone1
component [hosting_zone_2] <<Module>> as zone2

pro --> cdn
cdn --> cert
cdn --> s3
cdn --> redirect
pro --> dns
dns --> zone1
dns --> zone2

pro --> mails
mails --> ses1
mails --> ses2
mails --> email
@enduml
