name: "Terraform"

on: push

env:
  AWS_ACCESS_KEY_ID:  ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY:  ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_DEFAULT_REGION: eu-central-1

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Setup Terraform Linter
        uses: terraform-linters/setup-tflint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Terraform Linter plugins
        run: tflint --init

      - name: Terraform Linter
        run: tflint -f compact

      - name: Run Checkov action
        uses: bridgecrewio/checkov-action@master
        with:
          framework: terraform
